meta_title: "Code & Calanques"
meta_description: "Code & Calanques permet d'apprendre à coder en une semaine dans le cadre unique des calanques marseillaises"
meta_image: "social/home_facebook_card.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@lewagonaixmrs" # indispensable pour les Twitter Cards
fb_admin: 577765570
