meta_title: "Code & Calanque"
meta_description: "Apprenez à coder dans un cadre unique"
meta_image: "calanque_3.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@lewagonaixmrs" # indispensable pour les Twitter Cards
